CREATE DATABASE IF NOT EXISTS server12;
CREATE DATABASE IF NOT EXISTS empresarial2;
CREATE DATABASE IF NOT EXISTS tarifas;
CREATE DATABASE IF NOT EXISTS shalom_pro;
CREATE DATABASE IF NOT EXISTS shalom_clientes_corp;
CREATE DATABASE IF NOT EXISTS empresarial;